version: '3.5'

services:
  dynamodb:
    image: localstack/localstack
    container_name: localstack_dynamodb
    environment:
      SERVICES: "dynamodb"
      AWS_ACCESS_KEY_ID: fakeAccessKey
      AWS_SECRET_ACCESS_KEY: fakeSecretKey
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - localstack_dynamodb_data:/var/lib/localstack
    ports:
      - "4569:4569"

volumes:
  localstack_dynamodb_data:
    external: false
    name: localstack_dynamodb_data

# Database Access Credentials (replace with your actual credentials or use the default)
# AWS_ACCESS_KEY_ID: fakeAccessKey
# AWS_SECRET_ACCESS_KEY: fakeSecretKey
# AWS_DEFAULT_REGION: us-east-1
