services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: fakeAccessKey
      AWS_SECRET_ACCESS_KEY: fakeSecretKey
      AWS_REGION: us-east-1
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"

volumes:
  dynamodb_data:
    external: false
    name: dynamodb_data

# Database Access Credentials (replace with your actual credentials or use the default)
# AWS_ACCESS_KEY_ID: fakeAccessKey
# AWS_SECRET_ACCESS_KEY: fakeSecretKey
# AWS_REGION: us-east-1

# Credentials do not matter; they are not being verified anyway  

