version: '3.5' 

services: 
  db:
    image: mongo
    restart: always 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: 0 
    volumes: 
      - mongodb_local_data:/data/db 
    ports: 
      - 27017:27017 


volumes:
  mongodb_local_data:
    external: false
    name: mongodb_local_data

# Database Access Credentials (replace with your actual credentials or use the default)
# MONGO_INITDB_ROOT_USERNAME: root
# MONGO_INITDB_ROOT_PASSWORD: 0
