services:
  minio:
    image: minio/minio
    container_name: minio
    command: ["server", "/data", "--console-address", ":9001"]
    restart: always
    environment:
      MINIO_ROOT_USER: fakeAccessKey
      MINIO_ROOT_PASSWORD: fakeSecretKey
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port

volumes:
  minio_data:
    external: false
    name: minio_data

# Database Access Credentials (replace with your actual credentials or use the default)
# AWS_ACCESS_KEY_ID: fakeAccessKey
# AWS_SECRET_ACCESS_KEY: fakeSecretKey

# MINIO_ROOT_USER: fakeAccessKey
# MINIO_ROOT_PASSWORD: fakeSecretKey

# MinIO Console: http://localhost:9001
# API Compatible with AWS S3: http://localhost:9000