version: '3.5'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0
    volumes:
      - mysql_local_data:/var/lib/mysql
    ports:
      - 3306:3306
      
volumes:
  mysql_local_data:
    external: false
    name: mysql_local_data


# Database Access Credentials (replace with your actual credentials or use the default)
# USERNAME: root (default, no change)
# MYSQL_ROOT_PASSWORD: 0
