version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 0
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_local_data:
    external: false
    name: postgres_local_data

# Database Access Credentials (replace with your actual credentials or use the default)
# POSTGRES_USER: root
# POSTGRES_PASSWORD: 0
