version: "3.9"

services:
  node-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-dev
    tty: true
    stdin_open: true
    volumes:
      - ./workdir:/workspace
    working_dir: /workspace