version: '3.5'

services:
  db:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: 0
    volumes:
      - redis_local_data:/data
    ports:
      - 6379:6379

volumes:
  redis_local_data:
    external: false
    name: redis_local_data

# Database Access Credentials (replace with your actual credentials or use the default)
# REDIS_PASSWORD: 0
